server:
  port: 8081 # 端口

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  cloud:
    # Nacos 作为注册中心的配置项
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# Seata 配置项，对应 SeataProperties 类
seata:
  tx-service-group: order-service-group # 事务分组名称，服务名称+group组成
  service:
    vgroup-mapping:
      order-service-group: default # key是事务分组名称 value要和服务端的机房名称保持一致
