spring:
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 192.168.104.128 # RabbitMQ 服务的地址
    port: 5672 # RabbitMQ 服务的端口
    username: rabbituser # RabbitMQ 服务的账号
    password: 123456 # RabbitMQ 服务的密码
    listener:
      simple:
        acknowledge-mode: manual # 配置 Consumer 手动提交
